// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package mysql

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("packetbeat", "mysql", asset.ModuleFieldsPri, AssetMysql); err != nil {
		panic(err)
	}
}

// AssetMysql returns asset data.
// This is the base64 encoded zlib format compressed contents of protos/mysql.
func AssetMysql() string {
	return "eJy8lL+OGjEQxnue4tM1aYAHoEhzojjlQpRAlHJl7DFYeO1lPAZtnj7y7nKBwCWcIp0bkMfzzW/+7QQ7ameo27T3I0CceJrh4XO7/Pr8MAIMJc2uERfDDB9HANDZJqkh7azToAMFgXXkTZqOMPybdU8nCKqm3/LlSNvQDBuOuRluzj3OvbR3FGQqMfoX28l/R+0xsjm7v0F6Oo+d0ISpiSxk0HDcsKqrEmYMq7x3YYO10jtIRNXH7a0XOiFyrbz7Saa8y01DrFWiKb4vPi2+/FjAWeSgDsp5tfY0xWrrElyCChc6ORyInXVkoGMIpAs0lAi7dRYaI0SBgnBOBbfngTMUxEk7HV1VSllLWshUHI/pqlY+hs19hXqykC31HYaOda2CKfwpa00p2ezHkJJT17ICL8qF1DmdGC4rlus1MaJFISu/5alXSZBECdWlwdf5uJCIpXJ39nfAflos599W2Gfi9l5qZwaoS2w6+nagIFPYb0CGXFf96L6Jcjl/nj/+m7JYSMqcFae+jhdy0Q6LAybJHMi8wvjHTLwrYdf1v/B1Me6DW22pyPXfkgFOFXFlYDnWHYWwCkl1+/Sh2PaZ0q0BI+bIlY6G/mNbClEnhCL0kibWbb9Br8atKSW1obdGccFGDL63ov0KAAD///gYtSI="
}
